#!/usr/bin/env bash
# scripts/stamp-version.sh — Emit Sources/AppShell/Generated/VersionStamp.swift
# at build time so the running binary advertises its own provenance:
#   git short SHA + branch + dirty flag + buildKind (DEV / RELEASE).
#
# Used by dev-run.sh (kind=dev) and CI release.yml (kind=release). Generated
# file is .gitignored; commits never carry stale stamps.
#
# Env:
#   BUILD_KIND   "dev" (default) | "release"
#   VERSION      override (else read from genesis.json)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT_DIR="Sources/AppShell/Generated"
OUT_FILE="$OUT_DIR/VersionStamp.swift"
mkdir -p "$OUT_DIR"

BUILD_KIND="${BUILD_KIND:-dev}"
GENESIS_VERSION=$(python3 -c "import json; print(json.load(open('genesis.json')).get('version', ''))" 2>/dev/null || echo "")
VERSION="${VERSION:-${GENESIS_VERSION:-0.0.0.0}}"
VERSION="${VERSION#v}"

SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
# Dirty = uncommitted changes (staged or unstaged) present
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    DIRTY="true"
else
    DIRTY="false"
fi
BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > "$OUT_FILE" <<EOF
// Auto-generated by scripts/stamp-version.sh — DO NOT EDIT.
// Regenerated on every dev-run / release build. Source of truth for the
// in-app "build provenance" footer affordance.

public enum VersionStamp {
    public static let version: String = "$VERSION"
    public static let sha: String = "$SHA"
    public static let branch: String = "$BRANCH"
    public static let dirty: Bool = $DIRTY
    public static let buildKind: String = "$BUILD_KIND"
    public static let buildDate: String = "$BUILD_DATE"

    /// True when this build comes from a clean release tag, false otherwise.
    public static var isRelease: Bool { buildKind == "release" }

    /// Single-line summary suitable for footer / about dialog.
    /// Example DEV:     "v0.3.2.1 · DEV · 9f549f9 · main*"
    /// Example RELEASE: "v0.3.2.1 · 9f549f9"
    public static var summary: String {
        let dirtyMark = dirty ? "*" : ""
        if isRelease {
            return "v\(version) · \(sha)\(dirtyMark)"
        }
        return "v\(version) · DEV · \(sha) · \(branch)\(dirtyMark)"
    }
}
EOF

echo "[stamp] $OUT_FILE → v$VERSION · $BUILD_KIND · $SHA · $BRANCH (dirty=$DIRTY)"
